# .github/workflows/deploy.yml
name: Deploy Vue App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 获取源码
        uses: actions/checkout@v3

      - name: 进入 Vue 子项目目录
        run: cd my-vue-app

      - name: 安装依赖
        run: npm install
        working-directory: my-vue-app

      - name: 打包 Vue 应用
        run: npm run build
        working-directory: my-vue-app

      - name: 发布到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my-vue-app/dist
