# .github/workflows/deploy.yml
name: Deploy Vue App to GitHub Pages

on:
  push:
    branches:
      - main  # 每次 push 到 main 分支就触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 获取源码
        uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 安装依赖
        run: npm install
        working-directory: my-vue-app

      - name: 修复 vue-cli-service 执行权限
        run: chmod +x node_modules/.bin/vue-cli-service
        working-directory: my-vue-app

      - name: 打包 Vue 应用
        run: npm run build
        working-directory: my-vue-app

      - name: 发布到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my-vue-app/dist
